package app.paperkeep.core.data.fts

import io.mockk.every
import io.mockk.mockk
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey

/**
 * Unit tests for [OcrFtsIndex] using a software HMAC key.
 *
 * The Keystore-backed [OcrFtsKeyProvider] cannot run on the JVM, so we mock
 * it here and inject a software key generated by javax.crypto.
 */
class OcrFtsIndexTest {

    private lateinit var softwareKey: SecretKey
    private lateinit var index: OcrFtsIndex

    @Before
    fun setUp() {
        softwareKey = KeyGenerator.getInstance("HmacSHA256").generateKey()
        val keyProvider = mockk<OcrFtsKeyProvider>()
        every { keyProvider.getKey() } returns softwareKey
        index = OcrFtsIndex(keyProvider)
    }

    // ── normalize ─────────────────────────────────────────────────────────────

    @Test
    fun `normalize lowercases and strips non-alphanumeric`() {
        assertEquals("hello", index.normalize("Hello!"))
        assertEquals("hello123", index.normalize("Hello 123"))
        assertEquals("abc", index.normalize("A.b-c"))
    }

    @Test
    fun `normalize empty string returns empty`() {
        assertEquals("", index.normalize(""))
    }

    // ── tokenize ──────────────────────────────────────────────────────────────

    @Test
    fun `tokenize splits on whitespace and drops short tokens`() {
        val tokens = index.tokenize("Hello world hi")
        // tokenize preserves case; case-folding happens in normalize/hmacToken
        assertTrue("Hello" in tokens)
        assertTrue("world" in tokens)
        assertTrue("hi" !in tokens)   // length 2 — below MIN_TOKEN_LEN=3
        assertTrue("Hello" !in tokens.filter { it.length < 3 })
    }

    @Test
    fun `tokenize empty string returns empty list`() {
        assertTrue(index.tokenize("").isEmpty())
    }

    @Test
    fun `tokenize strips punctuation within words`() {
        val tokens = index.tokenize("don't stop")
        // "don't" → strip non-alpha → "dont" (4 chars → included)
        assertTrue(tokens.any { it == "dont" })
    }

    // ── hmacToken ─────────────────────────────────────────────────────────────

    @Test
    fun `hmacToken same input produces same output (deterministic)`() {
        assertEquals(index.hmacToken("invoice"), index.hmacToken("invoice"))
    }

    @Test
    fun `hmacToken different inputs produce different outputs`() {
        assertNotEquals(index.hmacToken("invoice"), index.hmacToken("receipt"))
    }

    @Test
    fun `hmacToken returns null for short tokens`() {
        assertNull(index.hmacToken("ab"))  // length 2
        assertNull(index.hmacToken(""))    // empty
    }

    @Test
    fun `hmacToken output is 64-char lowercase hex (SHA-256)`() {
        val token = index.hmacToken("hello")
        requireNotNull(token)
        assertEquals(64, token.length)
        assertTrue(token.all { it in '0'..'9' || it in 'a'..'f' })
    }

    @Test
    fun `hmacToken different key produces different output`() {
        val key2 = KeyGenerator.getInstance("HmacSHA256").generateKey()
        val provider2 = mockk<OcrFtsKeyProvider>()
        every { provider2.getKey() } returns key2
        val index2 = OcrFtsIndex(provider2)
        assertNotEquals(index.hmacToken("hello"), index2.hmacToken("hello"))
    }

    // ── indexText ─────────────────────────────────────────────────────────────

    @Test
    fun `indexText returns non-blank string for meaningful input`() {
        val result = index.indexText("Invoice from Acme Corp dated March 2024")
        assertTrue(result.isNotBlank())
    }

    @Test
    fun `indexText returns blank for only short tokens`() {
        assertTrue(index.indexText("ab cd ef").isBlank())
    }

    @Test
    fun `indexText tokens are space-separated hex strings`() {
        val result = index.indexText("hello world invoice")
        val tokens = result.split(" ")
        assertTrue(tokens.all { it.length == 64 && it.all { c -> c in '0'..'9' || c in 'a'..'f' } })
    }

    @Test
    fun `indexText deduplicates repeated words`() {
        val result = index.indexText("hello hello hello")
        val tokens = result.split(" ")
        assertEquals(1, tokens.size)
    }

    @Test
    fun `indexText output contains NO plaintext words`() {
        val result = index.indexText("confidential invoice secret salary")
        assertFalse(result.contains("confidential"))
        assertFalse(result.contains("invoice"))
        assertFalse(result.contains("secret"))
        assertFalse(result.contains("salary"))
    }

    // ── queryExpression ───────────────────────────────────────────────────────

    @Test
    fun `queryExpression appends star suffix to each token`() {
        val expr = index.queryExpression("hello world")
        val terms = expr.split(" ")
        assertTrue(terms.all { it.endsWith("*") })
    }

    @Test
    fun `queryExpression returns blank for all-short input`() {
        assertTrue(index.queryExpression("ab").isBlank())
    }

    @Test
    fun `queryExpression tokens match hmacToken output`() {
        val hmac = index.hmacToken("invoice")
        requireNotNull(hmac)
        val expr = index.queryExpression("invoice")
        assertTrue(expr.contains("$hmac*"))
    }

    // ── round-trip search simulation ─────────────────────────────────────────

    @Test
    fun `tokens indexed from OCR text are found by query expression`() {
        val ocrText = "Invoice number 12345 from Acme Corporation"
        val indexedTokens = index.indexText(ocrText)

        // Simulate a search for "acme"
        val queryExpr = index.queryExpression("acme")
        val searchToken = queryExpr.removeSuffix("*")

        // The indexed tokens should contain the exact HMAC for "acme"
        assertTrue(
            "Indexed tokens must contain the HMAC for 'acme'",
            indexedTokens.split(" ").contains(searchToken),
        )
    }

    companion object {
        private fun assertFalse(message: String, condition: Boolean) {
            assertTrue(message, !condition)
        }

        private fun assertFalse(condition: Boolean) = assertTrue(!condition)
    }
}
