#!/usr/bin/env bash
# get_api_url.sh — Read API Gateway URL from Terraform output and write to Android properties
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INFRA_DIR="${SCRIPT_DIR}/../infra"
ANDROID_PROPERTIES="${SCRIPT_DIR}/../android/core/network/api_base_url.properties"
BACKEND_ENV="${SCRIPT_DIR}/../backend/.env.generated"

# Ensure we're in the right workspace
ENVIRONMENT="${1:-staging}"

cd "$INFRA_DIR"
terraform workspace select "$ENVIRONMENT" 2>/dev/null || {
  echo "ERROR: Terraform workspace '${ENVIRONMENT}' not found. Run infra-bootstrap.sh first."
  exit 1
}

API_URL=$(terraform output -raw api_gateway_url)
if [[ -z "$API_URL" ]]; then
  echo "ERROR: api_gateway_url output is empty"
  exit 1
fi

echo "==> API Gateway URL: ${API_URL}"

# Write to Android properties
mkdir -p "$(dirname "$ANDROID_PROPERTIES")"
cat > "$ANDROID_PROPERTIES" <<EOF
# Auto-generated by scripts/get_api_url.sh — DO NOT COMMIT
API_BASE_URL=${API_URL}
EOF
echo "==> Written to ${ANDROID_PROPERTIES}"

# Write to backend generated env
cat > "$BACKEND_ENV" <<EOF
# Auto-generated by scripts/get_api_url.sh — DO NOT COMMIT
API_BASE_URL=${API_URL}
EOF
echo "==> Written to ${BACKEND_ENV}"

# Get TLS certificate pin for Android cert pinning
API_HOST=$(echo "$API_URL" | sed 's|https://||' | sed 's|/.*||')
echo "==> Getting TLS certificate pin for ${API_HOST}..."
PIN=$(echo | openssl s_client -connect "${API_HOST}:443" 2>/dev/null \
  | openssl x509 -pubkey -noout 2>/dev/null \
  | openssl pkey -pubin -outform der 2>/dev/null \
  | openssl dgst -sha256 -binary 2>/dev/null \
  | base64 2>/dev/null || echo "UNKNOWN")

PINS_FILE="${SCRIPT_DIR}/../android/core/network/pins.properties"
cat > "$PINS_FILE" <<EOF
# Auto-generated by scripts/get_api_url.sh — DO NOT COMMIT
TLS_PIN_SHA256=${PIN}
API_HOST=${API_HOST}
EOF
echo "==> TLS pin written to ${PINS_FILE}"
