// Package accounts implements account creation, email verification, and login.
package accounts

import (
	"context"
	"crypto/sha256"
	"errors"
	"fmt"
	"log/slog"
	"net/mail"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/nikhil/scanvault-api/internal/auth"
	"github.com/nikhil/scanvault-api/internal/config"
	"github.com/nikhil/scanvault-api/internal/db"
)

// -------------------------------------------------------------------------
// Sentinel errors
// -------------------------------------------------------------------------

var (
	ErrEmailTaken       = errors.New("email already registered")
	ErrInvalidEmail     = errors.New("invalid email address")
	ErrAccountNotFound  = errors.New("account not found")
	ErrBadCredentials   = errors.New("invalid credentials")
	ErrUnverified       = errors.New("email not verified")
	ErrTokenExpired     = errors.New("token expired or already used")
	ErrTokenNotFound    = errors.New("token not found")
	ErrRefreshRevoked   = errors.New("refresh token revoked")
	ErrRefreshExpired   = errors.New("refresh token expired")
	ErrAccountSuspended = errors.New("account suspended")
)

// -------------------------------------------------------------------------
// Request / response types
// -------------------------------------------------------------------------

type CreateAccountRequest struct {
	Email      string `json:"email"`
	AuthHash   string `json:"auth_hash"`    // Client-side Argon2id of password
	AuthParams string `json:"auth_params"`  // JSON: client Argon2id params
	WrappedKey []byte `json:"wrapped_key"`  // Client K_master wrapped with K_encrypt
	KDFSalt    []byte `json:"kdf_salt"`     // Salt for client-side KDF
	KDFParams  string `json:"kdf_params"`   // JSON: client KDF params
}

type CreateAccountResponse struct {
	UUID string `json:"uuid"`
}

type VerifyEmailRequest struct {
	Token string // from query string
}

type LoginRequest struct {
	Email    string `json:"email"`
	AuthHash string `json:"auth_hash"` // Client-side Argon2id of password
}

type LoginResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	// Crypto material the client needs to derive its local encryption keys
	WrappedKey string `json:"wrapped_key"`   // base64
	KDFSalt    string `json:"kdf_salt"`      // base64
	KDFParams  string `json:"kdf_params"`    // JSON string
}

type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// -------------------------------------------------------------------------
// Service
// -------------------------------------------------------------------------

// Service implements account management business logic.
type Service struct {
	pool                  *pgxpool.Pool
	q                     *db.Queries
	maker                 *auth.PasetoMaker
	cfg                   *config.Config
	logger                *slog.Logger
	lastVerificationToken string // test-only: last raw verification token issued
}

// LastVerificationToken returns the last raw verification token generated by
// CreateAccount. Used only in tests to retrieve the token without sending email.
func (s *Service) LastVerificationToken() string {
	return s.lastVerificationToken
}

// HashRefreshTokenExported is a test helper that exposes the internal
// refresh-token hash function so tests can manipulate DB state directly.
func HashRefreshTokenExported(raw string) []byte {
	return auth.HashRefreshToken(raw)
}

// New constructs a Service. Returns an error if the Paseto key is invalid.
func New(pool *pgxpool.Pool, cfg *config.Config, logger *slog.Logger) (*Service, error) {
	maker, err := auth.NewPasetoMaker(cfg.PasetoKey)
	if err != nil {
		return nil, fmt.Errorf("paseto maker: %w", err)
	}
	return &Service{
		pool:   pool,
		q:      db.New(pool),
		maker:  maker,
		cfg:    cfg,
		logger: logger,
	}, nil
}

// -------------------------------------------------------------------------
// CreateAccount (1A.9)
// -------------------------------------------------------------------------

// CreateAccount validates input, double-hashes the auth material server-side,
// stores the account, and issues an email verification token.
// Idempotent: calling with the same email within 1 minute returns the same UUID.
func (s *Service) CreateAccount(ctx context.Context, req CreateAccountRequest) (*CreateAccountResponse, error) {
	// Validate email syntax
	if err := validateEmail(req.Email); err != nil {
		return nil, ErrInvalidEmail
	}

	// Validate required fields
	if req.AuthHash == "" || req.AuthParams == "" || len(req.WrappedKey) == 0 || len(req.KDFSalt) == 0 || req.KDFParams == "" {
		return nil, fmt.Errorf("%w: missing required fields", ErrInvalidEmail)
	}

	// Check if email already exists.
	// Idempotency: if the account was created within the last minute (DB clock),
	// return the same UUID instead of an error. This absorbs client retries.
	_, emailErr := s.q.GetAccountByEmail(ctx, req.Email)
	if emailErr == nil {
		// Account exists — check freshness using DB-side NOW() to avoid clock skew.
		fresh, freshErr := s.q.GetAccountByEmailIfFresh(ctx, req.Email)
		if freshErr == nil {
			// Within idempotency window — return existing UUID
			uuidStr, uuidErr := uuidToString(fresh.Uuid)
			if uuidErr != nil {
				return nil, uuidErr
			}
			return &CreateAccountResponse{UUID: uuidStr}, nil
		}
		// Outside window (or other error) → treat as duplicate
		return nil, ErrEmailTaken
	}
	if !errors.Is(emailErr, pgx.ErrNoRows) {
		return nil, fmt.Errorf("checking email: %w", emailErr)
	}

	// Server-side double hash: server hashes the already-client-hashed material
	serverHash, err := auth.HashPassword(
		req.AuthHash,
		s.cfg.Argon2Time,
		s.cfg.Argon2Memory,
		s.cfg.Argon2Threads,
	)
	if err != nil {
		return nil, fmt.Errorf("hashing auth material: %w", err)
	}

	// Store auth params as JSON text
	authParamsText := pgtype.Text{String: req.AuthParams, Valid: true}
	kdfParamsText := pgtype.Text{String: req.KDFParams, Valid: true}

	account, err := s.q.CreateAccount(ctx, db.CreateAccountParams{
		Email:      req.Email,
		AuthHash:   serverHash,
		AuthParams: authParamsText,
		WrappedKey: req.WrappedKey,
		KdfSalt:    req.KDFSalt,
		KdfParams:  kdfParamsText,
	})
	if err != nil {
		// Postgres unique violation — race with another request
		if isUniqueViolation(err) {
			return nil, ErrEmailTaken
		}
		return nil, fmt.Errorf("creating account: %w", err)
	}

	// Issue email verification token
	rawToken, tokenHash, err := auth.GenerateVerificationToken()
	if err != nil {
		return nil, fmt.Errorf("generating verification token: %w", err)
	}

	expiresAt := pgtype.Timestamptz{Time: time.Now().Add(auth.VerificationTokenTTL), Valid: true}
	_, err = s.q.CreateEmailVerificationToken(ctx, db.CreateEmailVerificationTokenParams{
		AccountID: account.ID,
		TokenHash: tokenHash,
		ExpiresAt: expiresAt,
	})
	if err != nil {
		return nil, fmt.Errorf("storing verification token: %w", err)
	}

	// Email stub — log the token in dev; real Postmark integration in 1A.20
	s.lastVerificationToken = rawToken
	s.logger.Info("verification email (stub)",
		slog.String("email", req.Email),
		slog.String("token_preview", rawToken[:8]+"..."),
	)

	uuidStr, err := uuidToString(account.Uuid)
	if err != nil {
		return nil, err
	}
	return &CreateAccountResponse{UUID: uuidStr}, nil
}

// -------------------------------------------------------------------------
// VerifyEmail (1A.10)
// -------------------------------------------------------------------------

// VerifyEmail validates the token and marks the account as verified.
func (s *Service) VerifyEmail(ctx context.Context, rawToken string) error {
	hash := hashToken(rawToken)

	row, err := s.q.GetEmailVerificationTokenByHash(ctx, hash)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return ErrTokenNotFound
		}
		return fmt.Errorf("fetching token: %w", err)
	}

	// Already used
	if row.UsedAt.Valid {
		return ErrTokenExpired
	}

	// Expired
	if time.Now().After(row.ExpiresAt.Time) {
		return ErrTokenExpired
	}

	// Mark used
	if err := s.q.MarkEmailVerificationTokenUsed(ctx, row.ID); err != nil {
		return fmt.Errorf("marking token used: %w", err)
	}

	// Mark account verified
	if _, err := s.q.UpdateAccountEmailVerified(ctx, row.AccountID); err != nil {
		return fmt.Errorf("updating account verified: %w", err)
	}

	return nil
}

// -------------------------------------------------------------------------
// Login (1A.11)
// -------------------------------------------------------------------------

// Login authenticates a user with constant-time behaviour whether the account
// exists or not (prevents user-enumeration via timing).
func (s *Service) Login(ctx context.Context, req LoginRequest) (*LoginResponse, error) {
	account, err := s.q.GetAccountByEmail(ctx, req.Email)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// User does not exist — run dummy Argon2id to prevent timing leak
			auth.DummyVerify()
			return nil, ErrBadCredentials
		}
		return nil, fmt.Errorf("fetching account: %w", err)
	}

	// Verify password (constant-time)
	ok, err := auth.VerifyPassword(req.AuthHash, account.AuthHash)
	if err != nil {
		return nil, fmt.Errorf("verifying password: %w", err)
	}
	if !ok {
		return nil, ErrBadCredentials
	}

	// Check account status
	switch account.Status {
	case "suspended", "pending_deletion":
		return nil, ErrAccountSuspended
	}

	// Require email verification
	if !account.EmailVerified {
		return nil, ErrUnverified
	}

	// Mint access token
	uuidStr, err := uuidToString(account.Uuid)
	if err != nil {
		return nil, err
	}
	accessToken, err := s.maker.MakeAccessToken(auth.Claims{
		AccountID:   account.ID,
		AccountUUID: uuidStr,
		Email:       account.Email,
	})
	if err != nil {
		return nil, fmt.Errorf("minting access token: %w", err)
	}

	// Generate refresh token
	rawRefresh, refreshHash, err := auth.GenerateRefreshToken()
	if err != nil {
		return nil, fmt.Errorf("generating refresh token: %w", err)
	}

	expiresAt := pgtype.Timestamptz{Time: time.Now().Add(auth.RefreshTokenTTL), Valid: true}
	_, err = s.q.CreateRefreshToken(ctx, db.CreateRefreshTokenParams{
		AccountID:   account.ID,
		TokenHash:   refreshHash,
		DeviceLabel: nil,
		ExpiresAt:   expiresAt,
	})
	if err != nil {
		return nil, fmt.Errorf("storing refresh token: %w", err)
	}

	return &LoginResponse{
		AccessToken:  accessToken,
		RefreshToken: rawRefresh,
		WrappedKey:   encodeBase64(account.WrappedKey),
		KDFSalt:      encodeBase64(account.KdfSalt),
		KDFParams:    account.KdfParams.String,
	}, nil
}

// -------------------------------------------------------------------------
// Refresh (1A.12)
// -------------------------------------------------------------------------

// RefreshSession validates the refresh token, rotates it, and returns a new pair.
// Replay detection: if a revoked token is presented, ALL account tokens are revoked.
func (s *Service) RefreshSession(ctx context.Context, req RefreshRequest) (*RefreshResponse, error) {
	hash := auth.HashRefreshToken(req.RefreshToken)

	row, err := s.q.GetRefreshTokenByHash(ctx, hash)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrBadCredentials
		}
		return nil, fmt.Errorf("fetching refresh token: %w", err)
	}

	// Replay detection: revoked token presented → revoke ALL for account
	if row.RevokedAt.Valid {
		s.logger.Warn("replay attack detected — revoking all sessions",
			slog.Int64("account_id", row.AccountID))
		if rErr := s.q.RevokeAllRefreshTokensForAccount(ctx, row.AccountID); rErr != nil {
			s.logger.Error("failed to revoke all tokens", slog.String("error", rErr.Error()))
		}
		return nil, ErrRefreshRevoked
	}

	// Check expiry
	if time.Now().After(row.ExpiresAt.Time) {
		return nil, ErrRefreshExpired
	}

	// Load account for token claims
	account, err := s.q.GetAccountByID(ctx, row.AccountID)
	if err != nil {
		return nil, fmt.Errorf("fetching account: %w", err)
	}

	if account.Status != "active" {
		return nil, ErrAccountSuspended
	}

	// Revoke the old token
	if err := s.q.RevokeRefreshToken(ctx, row.ID); err != nil {
		return nil, fmt.Errorf("revoking old token: %w", err)
	}

	// Mint new access token
	uuidStr, err := uuidToString(account.Uuid)
	if err != nil {
		return nil, err
	}
	accessToken, err := s.maker.MakeAccessToken(auth.Claims{
		AccountID:   account.ID,
		AccountUUID: uuidStr,
		Email:       account.Email,
	})
	if err != nil {
		return nil, fmt.Errorf("minting access token: %w", err)
	}

	// Generate new refresh token
	rawRefresh, refreshHash, err := auth.GenerateRefreshToken()
	if err != nil {
		return nil, fmt.Errorf("generating refresh token: %w", err)
	}

	expiresAt := pgtype.Timestamptz{Time: time.Now().Add(auth.RefreshTokenTTL), Valid: true}
	_, err = s.q.CreateRefreshToken(ctx, db.CreateRefreshTokenParams{
		AccountID:   account.ID,
		TokenHash:   refreshHash,
		DeviceLabel: row.DeviceLabel,
		ExpiresAt:   expiresAt,
	})
	if err != nil {
		return nil, fmt.Errorf("storing new refresh token: %w", err)
	}

	return &RefreshResponse{
		AccessToken:  accessToken,
		RefreshToken: rawRefresh,
	}, nil
}

// -------------------------------------------------------------------------
// Helpers
// -------------------------------------------------------------------------

func validateEmail(email string) error {
	if len(email) > 254 {
		return errors.New("email too long")
	}
	_, err := mail.ParseAddress(email)
	return err
}

func isUniqueViolation(err error) bool {
	return err != nil && (contains(err.Error(), "23505") || contains(err.Error(), "unique"))
}

func contains(s, sub string) bool {
	return len(s) >= len(sub) && (s == sub || len(s) > 0 && containsStr(s, sub))
}

func containsStr(s, sub string) bool {
	for i := 0; i <= len(s)-len(sub); i++ {
		if s[i:i+len(sub)] == sub {
			return true
		}
	}
	return false
}

func uuidToString(u pgtype.UUID) (string, error) {
	if !u.Valid {
		return "", errors.New("invalid UUID")
	}
	b := u.Bytes
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
		b[0:4], b[4:6], b[6:8], b[8:10], b[10:16]), nil
}

func hashToken(raw string) []byte {
	sum := sha256.Sum256([]byte(raw))
	return sum[:]
}

func encodeBase64(b []byte) string {
	return fmt.Sprintf("%x", b)
}
