// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    email, auth_hash, auth_params,
    wrapped_key, kdf_salt, kdf_params
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uuid, email, email_verified, auth_hash, auth_params, wrapped_key, kdf_salt, kdf_params, status, created_at, updated_at
`

type CreateAccountParams struct {
	Email      string      `db:"email" json:"email"`
	AuthHash   string      `db:"auth_hash" json:"auth_hash"`
	AuthParams pgtype.Text `db:"auth_params" json:"auth_params"`
	WrappedKey []byte      `db:"wrapped_key" json:"wrapped_key"`
	KdfSalt    []byte      `db:"kdf_salt" json:"kdf_salt"`
	KdfParams  pgtype.Text `db:"kdf_params" json:"kdf_params"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Email,
		arg.AuthHash,
		arg.AuthParams,
		arg.WrappedKey,
		arg.KdfSalt,
		arg.KdfParams,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.EmailVerified,
		&i.AuthHash,
		&i.AuthParams,
		&i.WrappedKey,
		&i.KdfSalt,
		&i.KdfParams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, uuid, email, email_verified, auth_hash, auth_params, wrapped_key, kdf_salt, kdf_params, status, created_at, updated_at FROM accounts
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.EmailVerified,
		&i.AuthHash,
		&i.AuthParams,
		&i.WrappedKey,
		&i.KdfSalt,
		&i.KdfParams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByEmailIfFresh = `-- name: GetAccountByEmailIfFresh :one
SELECT id, uuid, email, email_verified, auth_hash, auth_params, wrapped_key, kdf_salt, kdf_params, status, created_at, updated_at FROM accounts
WHERE email = $1
  AND created_at > NOW() - INTERVAL '1 minute'
LIMIT 1
`

// Returns the account only if it was created within the last 1 minute (DB-side check).
func (q *Queries) GetAccountByEmailIfFresh(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmailIfFresh, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.EmailVerified,
		&i.AuthHash,
		&i.AuthParams,
		&i.WrappedKey,
		&i.KdfSalt,
		&i.KdfParams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, uuid, email, email_verified, auth_hash, auth_params, wrapped_key, kdf_salt, kdf_params, status, created_at, updated_at FROM accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.EmailVerified,
		&i.AuthHash,
		&i.AuthParams,
		&i.WrappedKey,
		&i.KdfSalt,
		&i.KdfParams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUUID = `-- name: GetAccountByUUID :one
SELECT id, uuid, email, email_verified, auth_hash, auth_params, wrapped_key, kdf_salt, kdf_params, status, created_at, updated_at FROM accounts
WHERE uuid = $1
LIMIT 1
`

func (q *Queries) GetAccountByUUID(ctx context.Context, uuid pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUUID, uuid)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.EmailVerified,
		&i.AuthHash,
		&i.AuthParams,
		&i.WrappedKey,
		&i.KdfSalt,
		&i.KdfParams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountAuthHash = `-- name: UpdateAccountAuthHash :one
UPDATE accounts
SET auth_hash   = $2,
    auth_params = $3,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, uuid, email, email_verified, auth_hash, auth_params, wrapped_key, kdf_salt, kdf_params, status, created_at, updated_at
`

type UpdateAccountAuthHashParams struct {
	ID         int64       `db:"id" json:"id"`
	AuthHash   string      `db:"auth_hash" json:"auth_hash"`
	AuthParams pgtype.Text `db:"auth_params" json:"auth_params"`
}

func (q *Queries) UpdateAccountAuthHash(ctx context.Context, arg UpdateAccountAuthHashParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountAuthHash, arg.ID, arg.AuthHash, arg.AuthParams)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.EmailVerified,
		&i.AuthHash,
		&i.AuthParams,
		&i.WrappedKey,
		&i.KdfSalt,
		&i.KdfParams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountEmailVerified = `-- name: UpdateAccountEmailVerified :one
UPDATE accounts
SET email_verified = TRUE,
    updated_at = NOW()
WHERE id = $1
RETURNING id, uuid, email, email_verified, auth_hash, auth_params, wrapped_key, kdf_salt, kdf_params, status, created_at, updated_at
`

func (q *Queries) UpdateAccountEmailVerified(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountEmailVerified, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.EmailVerified,
		&i.AuthHash,
		&i.AuthParams,
		&i.WrappedKey,
		&i.KdfSalt,
		&i.KdfParams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE accounts
SET status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, uuid, email, email_verified, auth_hash, auth_params, wrapped_key, kdf_salt, kdf_params, status, created_at, updated_at
`

type UpdateAccountStatusParams struct {
	ID     int64  `db:"id" json:"id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.ID, arg.Status)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.EmailVerified,
		&i.AuthHash,
		&i.AuthParams,
		&i.WrappedKey,
		&i.KdfSalt,
		&i.KdfParams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
