// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            int64              `db:"id" json:"id"`
	Uuid          pgtype.UUID        `db:"uuid" json:"uuid"`
	Email         string             `db:"email" json:"email"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	AuthHash      string             `db:"auth_hash" json:"auth_hash"`
	AuthParams    pgtype.Text        `db:"auth_params" json:"auth_params"`
	WrappedKey    []byte             `db:"wrapped_key" json:"wrapped_key"`
	KdfSalt       []byte             `db:"kdf_salt" json:"kdf_salt"`
	KdfParams     pgtype.Text        `db:"kdf_params" json:"kdf_params"`
	Status        string             `db:"status" json:"status"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EmailVerificationToken struct {
	ID        int64              `db:"id" json:"id"`
	AccountID int64              `db:"account_id" json:"account_id"`
	TokenHash []byte             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RefreshToken struct {
	ID          int64              `db:"id" json:"id"`
	AccountID   int64              `db:"account_id" json:"account_id"`
	TokenHash   []byte             `db:"token_hash" json:"token_hash"`
	DeviceLabel *string            `db:"device_label" json:"device_label"`
	LastUsedAt  pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
