// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	// Returns the account only if it was created within the last 1 minute (DB-side check).
	GetAccountByEmailIfFresh(ctx context.Context, email string) (Account, error)
	GetAccountByID(ctx context.Context, id int64) (Account, error)
	GetAccountByUUID(ctx context.Context, uuid pgtype.UUID) (Account, error)
	GetEmailVerificationTokenByHash(ctx context.Context, tokenHash []byte) (EmailVerificationToken, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	ListActiveRefreshTokensForAccount(ctx context.Context, accountID int64) ([]RefreshToken, error)
	MarkEmailVerificationTokenUsed(ctx context.Context, id int64) error
	RevokeAllRefreshTokensForAccount(ctx context.Context, accountID int64) error
	RevokeRefreshToken(ctx context.Context, id int64) error
	UpdateAccountAuthHash(ctx context.Context, arg UpdateAccountAuthHashParams) (Account, error)
	UpdateAccountEmailVerified(ctx context.Context, id int64) (Account, error)
	UpdateAccountKeyMaterial(ctx context.Context, arg UpdateAccountKeyMaterialParams) (Account, error)
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error)
	UpdateRefreshTokenLastUsed(ctx context.Context, id int64) (RefreshToken, error)
}

var _ Querier = (*Queries)(nil)
