// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (
    account_id, token_hash, expires_at
)
VALUES ($1, $2, $3)
RETURNING id, account_id, token_hash, expires_at, used_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	AccountID int64              `db:"account_id" json:"account_id"`
	TokenHash []byte             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    account_id, token_hash, device_label, expires_at
)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, token_hash, device_label, last_used_at, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	AccountID   int64              `db:"account_id" json:"account_id"`
	TokenHash   []byte             `db:"token_hash" json:"token_hash"`
	DeviceLabel *string            `db:"device_label" json:"device_label"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.AccountID,
		arg.TokenHash,
		arg.DeviceLabel,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.DeviceLabel,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const getEmailVerificationTokenByHash = `-- name: GetEmailVerificationTokenByHash :one
SELECT id, account_id, token_hash, expires_at, used_at, created_at FROM email_verification_tokens
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetEmailVerificationTokenByHash(ctx context.Context, tokenHash []byte) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenByHash, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, account_id, token_hash, device_label, last_used_at, expires_at, revoked_at, created_at FROM refresh_tokens
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.DeviceLabel,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveRefreshTokensForAccount = `-- name: ListActiveRefreshTokensForAccount :many
SELECT id, account_id, token_hash, device_label, last_used_at, expires_at, revoked_at, created_at FROM refresh_tokens
WHERE account_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY last_used_at DESC
`

func (q *Queries) ListActiveRefreshTokensForAccount(ctx context.Context, accountID int64) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listActiveRefreshTokensForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefreshToken{}
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TokenHash,
			&i.DeviceLabel,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerificationTokenUsed = `-- name: MarkEmailVerificationTokenUsed :exec
UPDATE email_verification_tokens
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkEmailVerificationTokenUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markEmailVerificationTokenUsed, id)
	return err
}

const revokeAllRefreshTokensForAccount = `-- name: RevokeAllRefreshTokensForAccount :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE account_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokensForAccount(ctx context.Context, accountID int64) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForAccount, accountID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const updateRefreshTokenLastUsed = `-- name: UpdateRefreshTokenLastUsed :one
UPDATE refresh_tokens
SET last_used_at = NOW()
WHERE id = $1
RETURNING id, account_id, token_hash, device_label, last_used_at, expires_at, revoked_at, created_at
`

func (q *Queries) UpdateRefreshTokenLastUsed(ctx context.Context, id int64) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, updateRefreshTokenLastUsed, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.DeviceLabel,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
