// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vault.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmPage = `-- name: ConfirmPage :one
UPDATE vault_pages
SET status = 'confirmed',
    version = version + 1
WHERE uuid = $1 AND deleted_at IS NULL
RETURNING id, uuid, document_id, page_index, r2_key, encrypted_size, checksum, status, version, created_at, deleted_at
`

func (q *Queries) ConfirmPage(ctx context.Context, uuid pgtype.UUID) (VaultPage, error) {
	row := q.db.QueryRow(ctx, confirmPage, uuid)
	var i VaultPage
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DocumentID,
		&i.PageIndex,
		&i.R2Key,
		&i.EncryptedSize,
		&i.Checksum,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one

INSERT INTO vault_documents (uuid, account_id, encrypted_metadata, metadata_nonce, page_count)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, uuid, account_id, encrypted_metadata, metadata_nonce, version, page_count, total_size_bytes, created_at, updated_at, deleted_at
`

type CreateDocumentParams struct {
	Uuid              pgtype.UUID `db:"uuid" json:"uuid"`
	AccountID         int64       `db:"account_id" json:"account_id"`
	EncryptedMetadata []byte      `db:"encrypted_metadata" json:"encrypted_metadata"`
	MetadataNonce     []byte      `db:"metadata_nonce" json:"metadata_nonce"`
	PageCount         int32       `db:"page_count" json:"page_count"`
}

// =========================================================================
// vault_documents queries
// =========================================================================
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (VaultDocument, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.Uuid,
		arg.AccountID,
		arg.EncryptedMetadata,
		arg.MetadataNonce,
		arg.PageCount,
	)
	var i VaultDocument
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.AccountID,
		&i.EncryptedMetadata,
		&i.MetadataNonce,
		&i.Version,
		&i.PageCount,
		&i.TotalSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPage = `-- name: CreatePage :one

INSERT INTO vault_pages (uuid, document_id, page_index, r2_key, encrypted_size, checksum)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uuid, document_id, page_index, r2_key, encrypted_size, checksum, status, version, created_at, deleted_at
`

type CreatePageParams struct {
	Uuid          pgtype.UUID `db:"uuid" json:"uuid"`
	DocumentID    int64       `db:"document_id" json:"document_id"`
	PageIndex     int32       `db:"page_index" json:"page_index"`
	R2Key         string      `db:"r2_key" json:"r2_key"`
	EncryptedSize int64       `db:"encrypted_size" json:"encrypted_size"`
	Checksum      []byte      `db:"checksum" json:"checksum"`
}

// =========================================================================
// vault_pages queries
// =========================================================================
func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (VaultPage, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.Uuid,
		arg.DocumentID,
		arg.PageIndex,
		arg.R2Key,
		arg.EncryptedSize,
		arg.Checksum,
	)
	var i VaultPage
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DocumentID,
		&i.PageIndex,
		&i.R2Key,
		&i.EncryptedSize,
		&i.Checksum,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const decrementQuotaUsage = `-- name: DecrementQuotaUsage :one
UPDATE account_quotas
SET storage_bytes_used = GREATEST(0, storage_bytes_used - $2),
    documents_count    = GREATEST(0, documents_count - $3),
    updated_at         = NOW()
WHERE account_id = $1
RETURNING account_id, storage_bytes_used, storage_bytes_limit, documents_count, documents_limit, updated_at
`

type DecrementQuotaUsageParams struct {
	AccountID        int64 `db:"account_id" json:"account_id"`
	StorageBytesUsed int64 `db:"storage_bytes_used" json:"storage_bytes_used"`
	DocumentsCount   int32 `db:"documents_count" json:"documents_count"`
}

func (q *Queries) DecrementQuotaUsage(ctx context.Context, arg DecrementQuotaUsageParams) (AccountQuota, error) {
	row := q.db.QueryRow(ctx, decrementQuotaUsage, arg.AccountID, arg.StorageBytesUsed, arg.DocumentsCount)
	var i AccountQuota
	err := row.Scan(
		&i.AccountID,
		&i.StorageBytesUsed,
		&i.StorageBytesLimit,
		&i.DocumentsCount,
		&i.DocumentsLimit,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByUUID = `-- name: GetDocumentByUUID :one
SELECT id, uuid, account_id, encrypted_metadata, metadata_nonce, version, page_count, total_size_bytes, created_at, updated_at, deleted_at FROM vault_documents
WHERE uuid = $1 AND account_id = $2 AND deleted_at IS NULL
`

type GetDocumentByUUIDParams struct {
	Uuid      pgtype.UUID `db:"uuid" json:"uuid"`
	AccountID int64       `db:"account_id" json:"account_id"`
}

func (q *Queries) GetDocumentByUUID(ctx context.Context, arg GetDocumentByUUIDParams) (VaultDocument, error) {
	row := q.db.QueryRow(ctx, getDocumentByUUID, arg.Uuid, arg.AccountID)
	var i VaultDocument
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.AccountID,
		&i.EncryptedMetadata,
		&i.MetadataNonce,
		&i.Version,
		&i.PageCount,
		&i.TotalSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDocumentByUUIDIncludeDeleted = `-- name: GetDocumentByUUIDIncludeDeleted :one
SELECT id, uuid, account_id, encrypted_metadata, metadata_nonce, version, page_count, total_size_bytes, created_at, updated_at, deleted_at FROM vault_documents
WHERE uuid = $1 AND account_id = $2
`

type GetDocumentByUUIDIncludeDeletedParams struct {
	Uuid      pgtype.UUID `db:"uuid" json:"uuid"`
	AccountID int64       `db:"account_id" json:"account_id"`
}

func (q *Queries) GetDocumentByUUIDIncludeDeleted(ctx context.Context, arg GetDocumentByUUIDIncludeDeletedParams) (VaultDocument, error) {
	row := q.db.QueryRow(ctx, getDocumentByUUIDIncludeDeleted, arg.Uuid, arg.AccountID)
	var i VaultDocument
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.AccountID,
		&i.EncryptedMetadata,
		&i.MetadataNonce,
		&i.Version,
		&i.PageCount,
		&i.TotalSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExpiredSoftDeletedDocuments = `-- name: GetExpiredSoftDeletedDocuments :many
SELECT id, uuid, account_id, encrypted_metadata, metadata_nonce, version, page_count, total_size_bytes, created_at, updated_at, deleted_at FROM vault_documents
WHERE deleted_at IS NOT NULL
  AND deleted_at < NOW() - INTERVAL '30 days'
LIMIT $1
`

func (q *Queries) GetExpiredSoftDeletedDocuments(ctx context.Context, limit int32) ([]VaultDocument, error) {
	rows, err := q.db.Query(ctx, getExpiredSoftDeletedDocuments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultDocument{}
	for rows.Next() {
		var i VaultDocument
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.AccountID,
			&i.EncryptedMetadata,
			&i.MetadataNonce,
			&i.Version,
			&i.PageCount,
			&i.TotalSizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredSoftDeletedPages = `-- name: GetExpiredSoftDeletedPages :many
SELECT p.id, p.uuid, p.document_id, p.page_index, p.r2_key, p.encrypted_size, p.checksum, p.status, p.version, p.created_at, p.deleted_at, d.account_id
FROM vault_pages p
JOIN vault_documents d ON d.id = p.document_id
WHERE p.deleted_at IS NOT NULL
  AND p.deleted_at < NOW() - INTERVAL '30 days'
LIMIT $1
`

type GetExpiredSoftDeletedPagesRow struct {
	ID            int64              `db:"id" json:"id"`
	Uuid          pgtype.UUID        `db:"uuid" json:"uuid"`
	DocumentID    int64              `db:"document_id" json:"document_id"`
	PageIndex     int32              `db:"page_index" json:"page_index"`
	R2Key         string             `db:"r2_key" json:"r2_key"`
	EncryptedSize int64              `db:"encrypted_size" json:"encrypted_size"`
	Checksum      []byte             `db:"checksum" json:"checksum"`
	Status        string             `db:"status" json:"status"`
	Version       int64              `db:"version" json:"version"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	AccountID     int64              `db:"account_id" json:"account_id"`
}

func (q *Queries) GetExpiredSoftDeletedPages(ctx context.Context, limit int32) ([]GetExpiredSoftDeletedPagesRow, error) {
	rows, err := q.db.Query(ctx, getExpiredSoftDeletedPages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExpiredSoftDeletedPagesRow{}
	for rows.Next() {
		var i GetExpiredSoftDeletedPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.DocumentID,
			&i.PageIndex,
			&i.R2Key,
			&i.EncryptedSize,
			&i.Checksum,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManifestSince = `-- name: GetManifestSince :many

SELECT uuid, version, updated_at, deleted_at
FROM vault_documents
WHERE account_id = $1
  AND updated_at > $2
  AND ($4::uuid IS NULL OR uuid > $4::uuid)
ORDER BY uuid ASC
LIMIT $3
`

type GetManifestSinceParams struct {
	AccountID int64              `db:"account_id" json:"account_id"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Limit     int32              `db:"limit" json:"limit"`
	AfterUuid pgtype.UUID        `db:"after_uuid" json:"after_uuid"`
}

type GetManifestSinceRow struct {
	Uuid      pgtype.UUID        `db:"uuid" json:"uuid"`
	Version   int64              `db:"version" json:"version"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// =========================================================================
// Sync manifest query
// =========================================================================
func (q *Queries) GetManifestSince(ctx context.Context, arg GetManifestSinceParams) ([]GetManifestSinceRow, error) {
	rows, err := q.db.Query(ctx, getManifestSince,
		arg.AccountID,
		arg.UpdatedAt,
		arg.Limit,
		arg.AfterUuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetManifestSinceRow{}
	for rows.Next() {
		var i GetManifestSinceRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Version,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateQuota = `-- name: GetOrCreateQuota :one

INSERT INTO account_quotas (account_id)
VALUES ($1)
ON CONFLICT (account_id) DO UPDATE
    SET updated_at = account_quotas.updated_at  -- no-op update to get the row back
RETURNING account_id, storage_bytes_used, storage_bytes_limit, documents_count, documents_limit, updated_at
`

// =========================================================================
// account_quotas queries
// =========================================================================
func (q *Queries) GetOrCreateQuota(ctx context.Context, accountID int64) (AccountQuota, error) {
	row := q.db.QueryRow(ctx, getOrCreateQuota, accountID)
	var i AccountQuota
	err := row.Scan(
		&i.AccountID,
		&i.StorageBytesUsed,
		&i.StorageBytesLimit,
		&i.DocumentsCount,
		&i.DocumentsLimit,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageByUUID = `-- name: GetPageByUUID :one
SELECT p.id, p.uuid, p.document_id, p.page_index, p.r2_key, p.encrypted_size, p.checksum, p.status, p.version, p.created_at, p.deleted_at, d.account_id
FROM vault_pages p
JOIN vault_documents d ON d.id = p.document_id
WHERE p.uuid = $1
  AND p.deleted_at IS NULL
`

type GetPageByUUIDRow struct {
	ID            int64              `db:"id" json:"id"`
	Uuid          pgtype.UUID        `db:"uuid" json:"uuid"`
	DocumentID    int64              `db:"document_id" json:"document_id"`
	PageIndex     int32              `db:"page_index" json:"page_index"`
	R2Key         string             `db:"r2_key" json:"r2_key"`
	EncryptedSize int64              `db:"encrypted_size" json:"encrypted_size"`
	Checksum      []byte             `db:"checksum" json:"checksum"`
	Status        string             `db:"status" json:"status"`
	Version       int64              `db:"version" json:"version"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	AccountID     int64              `db:"account_id" json:"account_id"`
}

func (q *Queries) GetPageByUUID(ctx context.Context, uuid pgtype.UUID) (GetPageByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getPageByUUID, uuid)
	var i GetPageByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DocumentID,
		&i.PageIndex,
		&i.R2Key,
		&i.EncryptedSize,
		&i.Checksum,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.AccountID,
	)
	return i, err
}

const getPagesByDocument = `-- name: GetPagesByDocument :many
SELECT id, uuid, document_id, page_index, r2_key, encrypted_size, checksum, status, version, created_at, deleted_at FROM vault_pages
WHERE document_id = $1 AND deleted_at IS NULL
ORDER BY page_index ASC
`

func (q *Queries) GetPagesByDocument(ctx context.Context, documentID int64) ([]VaultPage, error) {
	rows, err := q.db.Query(ctx, getPagesByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultPage{}
	for rows.Next() {
		var i VaultPage
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.DocumentID,
			&i.PageIndex,
			&i.R2Key,
			&i.EncryptedSize,
			&i.Checksum,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuota = `-- name: GetQuota :one
SELECT account_id, storage_bytes_used, storage_bytes_limit, documents_count, documents_limit, updated_at FROM account_quotas WHERE account_id = $1
`

func (q *Queries) GetQuota(ctx context.Context, accountID int64) (AccountQuota, error) {
	row := q.db.QueryRow(ctx, getQuota, accountID)
	var i AccountQuota
	err := row.Scan(
		&i.AccountID,
		&i.StorageBytesUsed,
		&i.StorageBytesLimit,
		&i.DocumentsCount,
		&i.DocumentsLimit,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteDocument = `-- name: HardDeleteDocument :exec
DELETE FROM vault_documents WHERE id = $1
`

func (q *Queries) HardDeleteDocument(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, hardDeleteDocument, id)
	return err
}

const hardDeletePage = `-- name: HardDeletePage :exec
DELETE FROM vault_pages WHERE id = $1
`

func (q *Queries) HardDeletePage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, hardDeletePage, id)
	return err
}

const incrementDocumentPageCount = `-- name: IncrementDocumentPageCount :one
UPDATE vault_documents
SET page_count        = page_count + 1,
    total_size_bytes  = total_size_bytes + $3,
    updated_at        = NOW()
WHERE id = $1
  AND account_id = $2
RETURNING id, uuid, account_id, encrypted_metadata, metadata_nonce, version, page_count, total_size_bytes, created_at, updated_at, deleted_at
`

type IncrementDocumentPageCountParams struct {
	ID             int64 `db:"id" json:"id"`
	AccountID      int64 `db:"account_id" json:"account_id"`
	TotalSizeBytes int64 `db:"total_size_bytes" json:"total_size_bytes"`
}

func (q *Queries) IncrementDocumentPageCount(ctx context.Context, arg IncrementDocumentPageCountParams) (VaultDocument, error) {
	row := q.db.QueryRow(ctx, incrementDocumentPageCount, arg.ID, arg.AccountID, arg.TotalSizeBytes)
	var i VaultDocument
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.AccountID,
		&i.EncryptedMetadata,
		&i.MetadataNonce,
		&i.Version,
		&i.PageCount,
		&i.TotalSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementQuotaUsage = `-- name: IncrementQuotaUsage :one
UPDATE account_quotas
SET storage_bytes_used = storage_bytes_used + $2,
    documents_count    = documents_count + $3,
    updated_at         = NOW()
WHERE account_id = $1
RETURNING account_id, storage_bytes_used, storage_bytes_limit, documents_count, documents_limit, updated_at
`

type IncrementQuotaUsageParams struct {
	AccountID        int64 `db:"account_id" json:"account_id"`
	StorageBytesUsed int64 `db:"storage_bytes_used" json:"storage_bytes_used"`
	DocumentsCount   int32 `db:"documents_count" json:"documents_count"`
}

func (q *Queries) IncrementQuotaUsage(ctx context.Context, arg IncrementQuotaUsageParams) (AccountQuota, error) {
	row := q.db.QueryRow(ctx, incrementQuotaUsage, arg.AccountID, arg.StorageBytesUsed, arg.DocumentsCount)
	var i AccountQuota
	err := row.Scan(
		&i.AccountID,
		&i.StorageBytesUsed,
		&i.StorageBytesLimit,
		&i.DocumentsCount,
		&i.DocumentsLimit,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, uuid, account_id, encrypted_metadata, metadata_nonce, version, page_count, total_size_bytes, created_at, updated_at, deleted_at FROM vault_documents
WHERE account_id = $1
  AND deleted_at IS NULL
  AND ($3::uuid IS NULL OR uuid > $3::uuid)
ORDER BY uuid ASC
LIMIT $2
`

type ListDocumentsParams struct {
	AccountID int64       `db:"account_id" json:"account_id"`
	Limit     int32       `db:"limit" json:"limit"`
	AfterUuid pgtype.UUID `db:"after_uuid" json:"after_uuid"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]VaultDocument, error) {
	rows, err := q.db.Query(ctx, listDocuments, arg.AccountID, arg.Limit, arg.AfterUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultDocument{}
	for rows.Next() {
		var i VaultDocument
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.AccountID,
			&i.EncryptedMetadata,
			&i.MetadataNonce,
			&i.Version,
			&i.PageCount,
			&i.TotalSizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageIndexExists = `-- name: PageIndexExists :one
SELECT EXISTS (
    SELECT 1 FROM vault_pages
    WHERE document_id = $1
      AND page_index = $2
      AND deleted_at IS NULL
) AS exists
`

type PageIndexExistsParams struct {
	DocumentID int64 `db:"document_id" json:"document_id"`
	PageIndex  int32 `db:"page_index" json:"page_index"`
}

func (q *Queries) PageIndexExists(ctx context.Context, arg PageIndexExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, pageIndexExists, arg.DocumentID, arg.PageIndex)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteDocument = `-- name: SoftDeleteDocument :one
UPDATE vault_documents
SET deleted_at = NOW(),
    updated_at  = NOW()
WHERE uuid = $1
  AND account_id = $2
  AND deleted_at IS NULL
RETURNING id, uuid, account_id, encrypted_metadata, metadata_nonce, version, page_count, total_size_bytes, created_at, updated_at, deleted_at
`

type SoftDeleteDocumentParams struct {
	Uuid      pgtype.UUID `db:"uuid" json:"uuid"`
	AccountID int64       `db:"account_id" json:"account_id"`
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) (VaultDocument, error) {
	row := q.db.QueryRow(ctx, softDeleteDocument, arg.Uuid, arg.AccountID)
	var i VaultDocument
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.AccountID,
		&i.EncryptedMetadata,
		&i.MetadataNonce,
		&i.Version,
		&i.PageCount,
		&i.TotalSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeletePage = `-- name: SoftDeletePage :one
UPDATE vault_pages
SET deleted_at = NOW()
WHERE uuid = $1 AND deleted_at IS NULL
RETURNING id, uuid, document_id, page_index, r2_key, encrypted_size, checksum, status, version, created_at, deleted_at
`

func (q *Queries) SoftDeletePage(ctx context.Context, uuid pgtype.UUID) (VaultPage, error) {
	row := q.db.QueryRow(ctx, softDeletePage, uuid)
	var i VaultPage
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DocumentID,
		&i.PageIndex,
		&i.R2Key,
		&i.EncryptedSize,
		&i.Checksum,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDocumentMetadata = `-- name: UpdateDocumentMetadata :one
UPDATE vault_documents
SET encrypted_metadata = $3,
    metadata_nonce      = $4,
    version             = version + 1,
    updated_at          = NOW()
WHERE uuid = $1
  AND account_id = $2
  AND version = $5
  AND deleted_at IS NULL
RETURNING id, uuid, account_id, encrypted_metadata, metadata_nonce, version, page_count, total_size_bytes, created_at, updated_at, deleted_at
`

type UpdateDocumentMetadataParams struct {
	Uuid              pgtype.UUID `db:"uuid" json:"uuid"`
	AccountID         int64       `db:"account_id" json:"account_id"`
	EncryptedMetadata []byte      `db:"encrypted_metadata" json:"encrypted_metadata"`
	MetadataNonce     []byte      `db:"metadata_nonce" json:"metadata_nonce"`
	Version           int64       `db:"version" json:"version"`
}

func (q *Queries) UpdateDocumentMetadata(ctx context.Context, arg UpdateDocumentMetadataParams) (VaultDocument, error) {
	row := q.db.QueryRow(ctx, updateDocumentMetadata,
		arg.Uuid,
		arg.AccountID,
		arg.EncryptedMetadata,
		arg.MetadataNonce,
		arg.Version,
	)
	var i VaultDocument
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.AccountID,
		&i.EncryptedMetadata,
		&i.MetadataNonce,
		&i.Version,
		&i.PageCount,
		&i.TotalSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
